---
title: "GCI-Go Reaches the Cloud: 2 Service Intances"
author: "Daniel Fireman (danielfireman@gmail.com)"
date: "January 12, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(resample)
require(dplyr)
require(stringr)

read.accesslog <- function(f) {
  # https://lincolnloop.com/blog/tracking-application-response-time-nginx/
  al <- read.csv(f, sep=";", colClasses=c("upstream_response_time"="character"))
  # request processing time in seconds with a milliseconds resolution;
  # time elapsed between the first bytes were read from the client and
  # the log write after the last bytes were sent to the client
  # http://nginx.org/en/docs/http/ngx_http_log_module.html.
  al$request_time <- al$request_time * 1000 # Making it milliseconds.
  # Calculating elapsed time. It is more useful than timestamp.
  al <- al %>% arrange(timestamp)
  al$exp_dur_ms <- c(0, al$timestamp[2:NROW(al)]-al$timestamp[1]) * 1000
  al$hop1 <- sub(',.*$', '', al$upstream_response_time)
  al$hop1 <- as.numeric(al$hop1)*1000
  al$hop2 <- sub('^.*,', '', al$upstream_response_time)
  al$hop2 <- as.numeric(al$hop2)*1000
  al$num_hops <- str_count(al$upstream_response_time, ',')+1
  return(al)
}

EXPERIMENT_DURATION <- 80000 # 80s

crop.accesslog <- function(al) {
  return(filter(al, exp_dur_ms > 10000 & exp_dur_ms < (EXPERIMENT_DURATION-10000)))
}

crop.gctrace <- function(t) {
  return(filter(t, time > 10000  & time < (EXPERIMENT_DURATION-10000)))
}
```

```{r nginx_al}
al.gci <- rbind(
  crop.accesslog(read.accesslog("/tmp/2instances/nginx_access_gci_300KB_5K_1.log")),
  crop.accesslog(read.accesslog("/tmp/2instances/nginx_access_gci_300KB_5K_2.log")),
  crop.accesslog(read.accesslog("/tmp/2instances/nginx_access_gci_300KB_5K_3.log")),
  crop.accesslog(read.accesslog("/tmp/2instances/nginx_access_gci_300KB_5K_4.log")),
  crop.accesslog(read.accesslog("/tmp/2instances/nginx_access_gci_300KB_5K_5.log")))
hist(al.gci$request_time, breaks=50)

al.nogci <- rbind(
  crop.accesslog(read.accesslog("/tmp/2instances/nginx_access_nogci_300KB_5K_1.log")),
  crop.accesslog(read.accesslog("/tmp/2instances/nginx_access_nogci_300KB_5K_2.log")),
  crop.accesslog(read.accesslog("/tmp/2instances/nginx_access_nogci_300KB_5K_3.log")),
  crop.accesslog(read.accesslog("/tmp/2instances/nginx_access_nogci_300KB_5K_4.log")),
  crop.accesslog(read.accesslog("/tmp/2instances/nginx_access_nogci_300KB_5K_5.log"))
)
hist(al.nogci$request_time, breaks=50)
```

```{r al_comp}
summary(al.gci)
summary(al.nogci)

quantile(al.gci$request_time, c(0.9,0.99,0.999,0.9999, 0.99999))
quantile(al.nogci$request_time, c(0.9,0.99,0.999,0.9999, 0.99999))

# Non parametric test which checks the pseudo-median
# https://en.wikipedia.org/wiki/Mann%E2%80%93Whitney_U_test
wilcox.test(sample(al.gci$request_time, 50000), conf.int = TRUE, conf.level = 0.95)
wilcox.test(sample(al.nogci$request_time, 50000), conf.int = TRUE, conf.level = 0.95)
```

```{r gctrace}
# Parsing some of gctrace fields and doing some cleanup.
read.gctrace <- function(f) {
  df <- read.csv(f, sep = " ")
  df$wallclock <- as.character(df$wallclock)
  df$walltime <-sapply(strsplit(df$wallclock, split="+", fixed=T) , function (x) sum(as.numeric(unlist(x))))
  df$time <- as.numeric(gsub("@|s","", df$time))*1000 # Making it elaspsed time in ms.
  df$isforced <- ifelse(is.na(df$isforced),0,df$isforced)
  return(na.omit(df))
}

gctrace.gci <- rbind(
  read.gctrace("/tmp/2instances/gctrace_gci_300KB_5K_0_1.out"),
  read.gctrace("/tmp/2instances/gctrace_gci_300KB_5K_1_1.out"),
  read.gctrace("/tmp/2instances/gctrace_gci_300KB_5K_0_2.out"),
  read.gctrace("/tmp/2instances/gctrace_gci_300KB_5K_1_2.out"),
  read.gctrace("/tmp/2instances/gctrace_gci_300KB_5K_0_3.out"),
  read.gctrace("/tmp/2instances/gctrace_gci_300KB_5K_1_3.out"),
  read.gctrace("/tmp/2instances/gctrace_gci_300KB_5K_0_4.out"),
  read.gctrace("/tmp/2instances/gctrace_gci_300KB_5K_1_4.out"),
  read.gctrace("/tmp/2instances/gctrace_gci_300KB_5K_0_5.out"),
  read.gctrace("/tmp/2instances/gctrace_gci_300KB_5K_1_5.out")
)
gctrace.nogci <- rbind(
  read.gctrace("/tmp/2instances/gctrace_nogci_300KB_5K_0_1.out"),
  read.gctrace("/tmp/2instances/gctrace_nogci_300KB_5K_1_1.out"),
  read.gctrace("/tmp/2instances/gctrace_nogci_300KB_5K_0_2.out"),
  read.gctrace("/tmp/2instances/gctrace_nogci_300KB_5K_1_2.out"),
  read.gctrace("/tmp/2instances/gctrace_nogci_300KB_5K_0_3.out"),
  read.gctrace("/tmp/2instances/gctrace_nogci_300KB_5K_1_3.out"),
  read.gctrace("/tmp/2instances/gctrace_nogci_300KB_5K_0_4.out"),
  read.gctrace("/tmp/2instances/gctrace_nogci_300KB_5K_1_4.out"),
  read.gctrace("/tmp/2instances/gctrace_nogci_300KB_5K_0_5.out"),
  read.gctrace("/tmp/2instances/gctrace_nogci_300KB_5K_1_5.out")
)

mean(gctrace.gci$walltime)
sd(gctrace.gci$walltime)
mean(gctrace.nogci$walltime)
sd(gctrace.nogci$walltime)
```

```{r}
requests_failed <- filter(al.gci, status != 200)
summary(requests_failed$request_time)
hist(requests_failed$request_time)
requests_failed %>% arrange(desc(request_time))

requests_resent <- filter(al.gci, num_hops > 1)
summary(requests_resent)
hist(requests_resent$request_time)
num_requests_resent <- requests_resent  %>% count()
requests_resent %>% arrange(desc(request_time))
summary(requests_resent$hop1)
hist(requests_resent$hop1)
summary(requests_resent$hop2)
hist(requests_resent$hop2)

requests_direct <- filter(al.gci, num_hops==1)
summary(requests_direct)
hist(requests_direct$request_time)
num_requests_direct <- requests_direct  %>% count()
requests_direct %>% arrange(desc(request_time))
```